musubi: musubi::buffer_pixmap< Format, Traits > Class Template Reference
musubi::buffer_pixmap< Format, Traits > Class Template Reference final
A memory-backed pixmap.
#include <pixmap.h>
Public Member Functions
buffer_pixmap (uint32 width, uint32 height) noexcept
Constructs a buffer_pixmap with the specified size.
buffer_pixmap (uint32 width, uint32 height, const byte *buffer)
Constructs a buffer_pixmap with the specified size, copying the specified buffer.
template<typename InputIterator >
buffer_pixmap (uint32 width, uint32 height, InputIterator first, InputIterator last)
Constructs a buffer_pixmap with the specified size, copying the specified range.
buffer_pixmap (buffer_pixmap &&other) noexcept
buffer_pixmap & operator= (buffer_pixmap &&other) noexcept
~buffer_pixmap () override=default
uint32 get_width () const override
uint32 get_height () const override
const byte * data () const override
pixmap_format get_format () const override
bool is_allocated () const noexcept
void ensure_buffer ()
Allocates a backing buffer for this pixmap if it does not have one.
byte * data ()
Traits::element_type get_pixel (uint32 x, uint32 y) const
Retrieves the data of a specified pixel.
void set_pixel (uint32 x, uint32 y, typename Traits::element_type value)
Sets the value of a specified pixel.
Public Member Functions inherited from musubi::pixmap
virtual ~pixmap ()
Detailed Description
template<pixmap_format Format, typename Traits = pixmap_traits<Format>>
class musubi::buffer_pixmap< Format, Traits >
A memory-backed pixmap.
Template Parameters
Format this pixmap's data format
Traits the pixmap_traits for this pixmap's data
A backing buffer for a new, empty pixmap is not allocated until an attempt is made to actually modify the underlying buffer.
Definition at line 118 of file pixmap.h.
Constructor & Destructor Documentation
buffer_pixmap() [1/4]
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> musubi::buffer_pixmap< Format, Traits >::buffer_pixmap (uint32 width, uint32 height) inline noexcept
Constructs a buffer_pixmap with the specified size.
This does not allocate any memory.
Parameters
[in] width,height the pixmap size
Definition at line 123 of file pixmap.h.
                 : width(width), height(height), buffer(nullptr) {}
buffer_pixmap() [2/4]
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> musubi::buffer_pixmap< Format, Traits >::buffer_pixmap (uint32 width, uint32 height, const byte * buffer) inline
Constructs a buffer_pixmap with the specified size, copying the specified buffer.
Parameters
[in] width,height the pixmap size
[in] buffer the source buffer to load
Definition at line 129 of file pixmap.h.
References std::copy().
                 : width(width), height(height) {
             ensure_buffer();
             std::copy(buffer, buffer + get_buffer_size(width, height), this->buffer.get());
         }
buffer_pixmap() [3/4]
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> template<typename InputIterator > musubi::buffer_pixmap< Format, Traits >::buffer_pixmap (uint32 width, uint32 height, InputIterator first, InputIterator last) inline
Constructs a buffer_pixmap with the specified size, copying the specified range.
Template Parameters
InputIterator the range iterator type
Parameters
[in] width,height the pixmap size
[in] first,last the data range to copy from
Definition at line 140 of file pixmap.h.
References std::copy().
                 : width(width), height(height) {
             ensure_buffer();
             std::copy(first, last, buffer.get());
         }
buffer_pixmap() [4/4]
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> musubi::buffer_pixmap< Format, Traits >::buffer_pixmap (buffer_pixmap< Format, Traits > && other) inline noexcept
Move constructor; other becomes an empty but valid pixmap.
Parameters
[in,out] other the pixmap to move from
Definition at line 148 of file pixmap.h.
                 : width(other.width), height(other.height),
                   buffer(std::move(other.buffer)) {}
~buffer_pixmap()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> musubi::buffer_pixmap< Format, Traits >::~buffer_pixmap () override default
Destroys this pixmap and releases its resources.
Member Function Documentation
data() [1/2]
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> const byte* musubi::buffer_pixmap< Format, Traits >::data () const inline override virtual
Retrieves a const pointer to this pixmap's data.
Returns
a const pointer to this pixmap's data
Implements musubi::pixmap.
Definition at line 169 of file pixmap.h.
 { return buffer.get(); }
data() [2/2]
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> byte* musubi::buffer_pixmap< Format, Traits >::data () inline
Retrieves a mutable pointer to this pixmap's data.
Returns
a mutable pointer to this pixmap's data
Definition at line 188 of file pixmap.h.
 { return buffer.get(); }
ensure_buffer()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> void musubi::buffer_pixmap< Format, Traits >::ensure_buffer () inline
Allocates a backing buffer for this pixmap if it does not have one.
Does nothing otherwise.
See also
is_allocated()
Definition at line 180 of file pixmap.h.
{
             if (!is_allocated()) {
                 buffer = std::make_unique<byte[]>(get_buffer_size(width, height));
             }
         }
get_format()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> pixmap_format musubi::buffer_pixmap< Format, Traits >::get_format () const inline override virtual
Retrieves this pixmap's data format.
Returns
this pixmap's data format
Implements musubi::pixmap.
Definition at line 171 of file pixmap.h.
 { return Format; }
get_height()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> uint32 musubi::buffer_pixmap< Format, Traits >::get_height () const inline override virtual
Retrieves the height of this pixmap, in pixels.
Returns
the height of this pixmap in pixels
Implements musubi::pixmap.
Definition at line 167 of file pixmap.h.
 { return height; }
get_pixel()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> Traits::element_type musubi::buffer_pixmap< Format, Traits >::get_pixel (uint32 x, uint32 y) const inline
Retrieves the data of a specified pixel.
Parameters
[in] x,y the position of the pixel
Returns
the value of the specified pixel
Definition at line 193 of file pixmap.h.
References std::to_string().
{
             if (x >= width) {
                 throw std::out_of_range(
                         "x out of pixmap range: "s + std::to_string(x) + " >= "s + std::to_string(width)
                 );
             } else if (y >= height) {
                 throw std::out_of_range(
                         "y out of pixmap range: "s + std::to_string(y) + " >= "s + std::to_string(height)
                 );
             }
             // Combine bytes_per_pixel bytes into a single element_type
             typename Traits::element_type result{0u};
             if (!is_allocated()) return result;
             const auto ptr = get_ptr(x, y);
             const auto max{Traits::get_bytes_per_pixel()};
             for (auto i = 0u; i < max; ++i) {
                 result |= (static_cast<typename Traits::element_type>(ptr[i]) << ((max - i - 1) * 8));
             }
             return result;
         }
get_width()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> uint32 musubi::buffer_pixmap< Format, Traits >::get_width () const inline override virtual
Retrieves the width of this pixmap, in pixels.
Returns
the width of this pixmap in pixels
Implements musubi::pixmap.
Definition at line 165 of file pixmap.h.
 { return width; }
is_allocated()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> bool musubi::buffer_pixmap< Format, Traits >::is_allocated () const inline noexcept
Checks if this pixmap has allocated a backing buffer.
Returns
whether this pixmap has allocated a backing buffer
Definition at line 175 of file pixmap.h.
 { return buffer.operator bool(); }
operator=()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> buffer_pixmap& musubi::buffer_pixmap< Format, Traits >::operator= (buffer_pixmap< Format, Traits > && other) inline noexcept
Move assignment operator; other becomes an empty but valid pixmap.
Parameters
[in,out] other the pixmap to move from
Returns
this
Definition at line 155 of file pixmap.h.
{
             width = other.width;
             height = other.height;
             buffer = std::move(other.buffer);
             return *this;
         }
set_pixel()
template<pixmap_format Format, typename Traits = pixmap_traits<Format>> void musubi::buffer_pixmap< Format, Traits >::set_pixel (uint32 x, uint32 y, typename Traits::element_type value) inline
Sets the value of a specified pixel.
Parameters
[in] x,y the position of the pixel
[in] value the new value of the pixel
Definition at line 217 of file pixmap.h.
References std::to_string().
{
             // Decompose a element_type into bytes_per_pixel bytes
             if (x >= width) {
                 throw std::out_of_range(
                         "x out of pixmap range: "s + std::to_string(x) + " >= "s + std::to_string(width)
                 );
             } else if (y >= height) {
                 throw std::out_of_range(
                         "y out of pixmap range: "s + std::to_string(y) + " >= "s + std::to_string(height)
                 );
             }
             ensure_buffer();
             const auto ptr = get_ptr(x, y);
             const auto max{Traits::bytes_per_pixel};
             for (auto i = 0u; i < max; ++i) {
                 ptr[i] = static_cast<byte>((value >> ((max - i - 1) * 8)) & 0xFFu);
             }
         }
The documentation for this class was generated from the following file:
musubi/include/musubi/pixmap.h