musubi: musubi::sdl::sdl_window Class Reference
musubi::sdl::sdl_window Class Reference
An SDL window with an OpenGL context.
#include <sdl_window.h>
Public Types
using poller_type = sdl_input_poller
Public Types inherited from musubi::window
using id_type = uint32
The unique ID type used internally to identify windows.
Public Member Functions
sdl_window (const start_info &startInfo)
sdl_window (const start_info &startInfo, std::unique_ptr< screen > initialScreen)
sdl_window (sdl_window &&other) noexcept
sdl_window & operator= (sdl_window &&other) noexcept
~sdl_window () override
Destroys this wrapper and the associated SDL window.
void set_screen (std::unique_ptr< screen > newScreen) final
Sets this window's current screen.
template<typename Screen , typename... ScreenArgs>
std::enable_if_t< std::is_base_of_v< screen, Screen >, void > set_screen (ScreenArgs &&...args)
Constructs a screen by forwarding the specified arguments to the constructor of Screen, and makes it the current screen.
void update (const input_state &inputState) override
Performs a tick.
id_type get_id () const override
void make_current () const
Makes this window's OpenGL context current.
void flip () const
Swaps this window's buffers.
Public Member Functions inherited from musubi::window
virtual ~window ()=default
Closes and destroys this window.
Detailed Description
An SDL window with an OpenGL context.
Definition at line 23 of file sdl_window.h.
Member Typedef Documentation
poller_type
using musubi::sdl::sdl_window::poller_type = sdl_input_poller
The associated input_poller implementation.
See also
sdl_input_poller
Definition at line 27 of file sdl_window.h.
Constructor & Destructor Documentation
sdl_window() [1/3]
musubi::sdl::sdl_window::sdl_window (const start_info & startInfo) explicit
Constructs an SDL window from the specified start_info.
Parameters
startInfo initialization parameters
sdl_window() [2/3]
musubi::sdl::sdl_window::sdl_window (const start_info & startInfo, std::unique_ptr< screen > initialScreen)
Constructs an SDL window from the specified start_info and initial screen.
Parameters
startInfo initialization parameters
initialScreen the initial screen
See also
set_screen()
sdl_window() [3/3]
musubi::sdl::sdl_window::sdl_window (sdl_window && other) noexcept
Move constructor; other becomes invalid.
Parameters
[in,out] other the window to move from
Member Function Documentation
get_id()
id_type musubi::sdl::sdl_window::get_id () const override virtual
Retrieves this window's internal identifier.
Returns
this window's ID
Implements musubi::window.
Referenced by set_screen().
operator=()
sdl_window& musubi::sdl::sdl_window::operator= (sdl_window && other) noexcept
Move assignment operator; other becomes invalid.
Parameters
[in,out] other the window to move from
Returns
this
set_screen() [1/2]
void musubi::sdl::sdl_window::set_screen (std::unique_ptr< screen > newScreen) final virtual
Sets this window's current screen.
The old screen instance is destroyed.
Parameters
newScreen the new screen
Implements musubi::window.
set_screen() [2/2]
template<typename Screen , typename... ScreenArgs> std::enable_if_t<std::is_base_of_v<screen, Screen>, void> musubi::sdl::sdl_window::set_screen (ScreenArgs &&... args) inline
Constructs a screen by forwarding the specified arguments to the constructor of Screen, and makes it the current screen.
The old screen instance is destroyed.
Template Parameters
Screen the screen type
ScreenArgs a parameter pack to hold the forwarded arguments
Parameters
args the arguments to forward to the constructor of Screen
Definition at line 66 of file sdl_window.h.
References flip(), get_id(), make_current(), set_screen(), and update().
Referenced by set_screen().
 { set_screen(std::make_unique<Screen>(std::forward<ScreenArgs>(args)...)); }
update()
void musubi::sdl::sdl_window::update (const input_state & inputState) override virtual
Performs a tick.
This function is typically called from the application's event loop.
Parameters
inputState the current window input state
Implements musubi::window.
Referenced by set_screen().
The documentation for this class was generated from the following file:
musubi/include/musubi/sdl/sdl_window.h